version: '3'
services:
  itsmdb :
    image: mysql:8.0
    container_name: itsmdb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes :
      - ./itsmdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpwd
      MYSQL_USER : itsmng
      MYSQL_PASSWORD : itsmng
      MYSQL_DATABASE : itsmng
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
  itsmweb :
    image : webdevops/php-apache:7.4
    container_name : itsmweb
    restart: always
    ports :
      - "127.0.0.1:9080:80"
    volumes :
      - ./itsmng:/app
    environment:
      WEB_DOCUMENT_INDEX : index.php