version: '3'
services:
  itsmweb :
    image : itsm-ng
    depends_on:
      - itsmdb
    container_name : itsmweb
    restart: always
    ports :
      - "80:80"
    volumes :
      - ../itsmng-config:/var/www/itsm-ng/config
      - ../itsmng-plugins:/var/www/itsm-ng/plugins
      - ../itsmng-files:/var/www/itsm-ng/files
    environment:
      MARIADB_USER : itsmng
      MARIADB_PASSWORD : itsmng
      MARIADB_DATABASE : itsmng
  itsmdb :
    image: mariadb
    container_name: itsmdb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes :
      - ../itsmdata:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: "yes"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_USER : itsmng
      MARIADB_PASSWORD : itsmng
      MARIADB_DATABASE : itsmng
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
